server:
  port: 8282

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    enabled: false

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

logging:
  level:
    ROOT: ERROR
    com.bootcamp: ERROR
    org.springframework: ERROR
    org.springframework.kafka: ERROR
    io.confluent: ERROR
pattern:
  console: "%d %-5level %logger : %msg%n"

kafka:
  bootstrap-servers: ${BOOTSTRAP_HOST:localhost}:9092
  schema-registry: http://${SCHEMA_HOST:localhost}:8081
  consumer:
    auto-commit-interval-in-ms: 100
    enable-auto-commit: false
    session-timeout-in-ms: 30000
    auto-offset-reset: earliest
    fetch-max-wait-in-ms: 200
    max-partition-fetch-bytes: 50331648
    min-partition-fetch-bytes: 50331648
    max-poll-records: 100
    concurrency-level: 1
    consumer-group-id: cdc-consumer-27
    indv:
      topic-name: cdc-indvinq
    org:
      topic-name: cdc-orginq
  publisher:
    buffer-memory: 33554432
    linger-time-in-ms: 5
    publish-batch-size: 16384
    retry-count: 0
    indv:
      topic-name: avro-indvinq
      error-topic: cdc-indvinq-error
    org:
      topic-name: avro-orginq
      error-topic: cdc-orginq-error
