server:
  port: 8282

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: false


logging:
  level:
    ROOT: ERROR
    com.bootcamp: DEBUG
    org.springframework: ERROR
    org.springframework.kafka: DEBUG
    io.confluent: DEBUG
pattern:
  console: "%d %-5level %logger : %msg%n"


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PRT:3306}/${DB_NAME:cdcEvent}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:passw0rd}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          order_inserts: true
        generate_statistics: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

kafka:
  bootstrap-servers: ${BOOTSTRAP_HOST:localhost}:9092
  schema-registry: http://${SCHEMA_HOST:localhost}:8081
  consumer:
    auto-commit-interval-in-ms: 100
    enable-auto-commit: false
    session-timeout-in-ms: 30000
    auto-offset-reset: earliest
    fetch-max-wait-in-ms: 200
    max-partition-fetch-bytes: 50331648
    min-partition-fetch-bytes: 50331648
    max-poll-records: 1000
    consumer-group-id: event-consumer-63
    concurrency-level: 5
    indv:
      topic-name: avro-indvinq
    org:
      topic-name: avro-orginq
