server:
  port: 8284

management:
  endpoints:
    web:
      exposure:
        include: '*'
#disable eureka client discovery
#eureka:
#  client:
#    enabled: false


logging:
  level:
    ROOT: ERROR
    com.bootcamp: DEBUG
    org.springframework: ERROR
    org.springframework.kafka: DEBUG
    io.confluent: DEBUG
pattern:
  console: "%d %-5level %logger : %msg%n"

#sepify none as dll-auto : if you care about database not to be destroyed for select only
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PRT:3306}/${DB_NAME:cdcEvent}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:passw0rd}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          order_inserts: true
        generate_statistics: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
